name       : rymdport
version    : 3.3.5
release    : 4
source     :
    - https://github.com/Jacalz/rymdport/releases/download/v3.3.5/rymdport-v3.3.5-vendored.tar.xz : a64390dade67db6ddc09d7d5f96bff21051f630708ae52a128db7f264b53cf56
license    : GPL-3.0-or-later
homepage   : https://github.com/Jacalz/rymdport
component  : network.clients
summary    : Easy encrypted file, folder, and text sharing between devices.
description: |
    Rymdport (formerly wormhole-gui) is a cross-platform application that lets you easily and safely share files, folders, and text between devices. The data is sent securely with end-to-end encryption using the same protocol as magic-wormhole. This means that Rymdport can talk not only to itself, but also to other wormhole clients.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
    - golang
build      : |
    go build -trimpath -o rymdport
install    : |
    %make_install
    install -Dm00644 "$installdir/usr/share/icons/hicolor/512x512/io.github.jacalz.rymdport.png" "$installdir/usr/share/pixmaps/io.github.jacalz.rymdport.png"   
    install -Dm00644 "$installdir/usr/share/icons/hicolor/scalable/io.github.jacalz.rymdport.svg" "$installdir/usr/share/pixmaps/io.github.jacalz.rymdport.svg"
    rm -rf "$installdir/usr/share/icons"
