name       : rymdport
version    : 3.5.0
release    : 7
source     :
    - https://github.com/Jacalz/rymdport/releases/download/v3.5.0/rymdport-v3.5.0-vendored.tar.xz : 5d6b62964987a6acefa84be5ca02d0303d86f0e812a86a6622d3c56a86d9c43f
license    : GPL-3.0-or-later
homepage   : https://github.com/Jacalz/rymdport
component  : network.clients
summary    : Easy encrypted file, folder, and text sharing between devices.
description: |
    Rymdport (formerly wormhole-gui) is a cross-platform application that lets you easily and safely share files, folders, and text between devices. The data is sent securely with end-to-end encryption using the same protocol as magic-wormhole. This means that Rymdport can talk not only to itself, but also to other wormhole clients.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
    - golang
setup      : |
    %patch -p1 -i $pkgfiles/dont-update-icon-cache.patch
build      : |
    go build -tags no_emoji -trimpath -ldflags="-s -w" -buildvcs=false -o rymdport
install    : |
    %make_install
